Fix StdConfig#setCmdLineArgs (#509)
eeverman/andhow pull request #556
Opened 2021-08-19 20:25 UTC by alex-kar

Fixes #509

* Update setter to remove previously set arguments.
* Cover with test.
* Update javadoc.

### All Submissions:

Have you checked that...
* [+] Your pull request is to the *_main_* branch
* [+] Your code is up to date with the latest code from the *_main_*
* [+] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [+] Your code does not decrease test coverage (maybe it improves coverage!!)
* [+] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-08-19 21:59 UTC, eeverman requested changes
Nice fix!  One minor comment on the tests.
Thanks again!

2021-08-19 21:59 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigGetterAndSetterTest.java
> +		config.setCmdLineArgs(new String[0]);
Oops, this test doesn't test the null.  Also, to really test it, it should initially be set non-empty.

2021-08-19 22:08 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigGetterAndSetterTest.java
> +		config.setCmdLineArgs(new String[0]);
Fixed

2021-08-20 00:27 UTC, eeverman approved these changes
Looks great!

2021-08-20 00:28 UTC, merged