MapLoader#setMap should copy the map (#554)
eeverman/andhow pull request #564
Opened 2021-08-22 21:59 UTC by alex-kar

Fixes #554 

* Fix MapLoader
* Cover with unit tests

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-08-23 02:13 UTC, eeverman requested changes
Great Work - I love the added tests!

Unfortunately, I gave you some bad information.  I think the changes are small to fix my mistake, but I am very sorry.

2021-08-23 02:13 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java
> +
My mistake - This will have to stay null.  Please see my comments in the issue.

2021-08-23 02:13 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java
> +		if (!props.isEmpty()) {
I think think this will need to be `if (props != null && ! props.isEmpty()) { ...`

2021-08-23 02:13 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java
> +		this.map = map == null ? Collections.emptyMap() : new HashMap<>(map);
See issue comments.

2021-08-23 02:13 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java
> +		map.clear();
This can go back to null.

2021-08-23 02:13 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java
> +		if (!map.isEmpty()) {
This logic will need to go back to `if (map !- null)`.

The problem is that this Loader needs to distinguish between an empty map and a null map:
*  If the map is null, just use the real System.Properties
* If the map is non-null, someone is trying to override the real system properties with different values.  They may choose to override the System Properties with an empty map, meaning that they are simulating the case where there are no Sys Props.

`StdEnvVarLoader` will have the same issue.

2021-08-23 09:39 UTC, alex-kar commented
@eeverman Thank you for your comments, please review fixes that I pushed.

2021-08-23 17:53 UTC, eeverman requested changes
I added a few small test improvements, but this is great work!

2021-08-23 17:53 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +    }
This is a really good test of behavior - Thank you.

2021-08-23 17:53 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +        args.put(basePath + "STR_ENDS_WITH_XXX", "XXX");
One suggestion:  Add some spaces around some of these values, eg:
```
args.put(basePath + "STR_BOB", "     test    ");
```
The trimmer should remove the spaces, so the result should be the same.  I should have done that in some of my tests as well.

2021-08-23 17:53 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +    }
This would be a good one to add a behavior test for.  `KeyValuePairTest.testCmdLineLoaderWithUnknownProperties` is an example where this is tested.  When `isUnknownPropertyAProblem` is True, there should a 'Problem' when the loader hits an unrecognized property.  When it is false, the loader should quietly ignore them.

2021-08-23 17:55 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java
> +		map.clear();
Either way works here.

2021-08-23 19:53 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +        args.put(basePath + "STR_ENDS_WITH_XXX", "XXX");
Fixed

2021-08-23 19:55 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +    }
Fixed. Please, let me know if this is what you expected.

2021-08-23 23:34 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
> +    }
Yep, you got it.  Nice added test.

2021-08-23 23:37 UTC, eeverman approved these changes
Great - Nice work!
I think I have given you permissions to merge this - are you able to?

2021-08-24 05:37 UTC, merged

2021-08-24 05:39 UTC, alex-kar commented
@eeverman Thank you, I've merged it.