JDK 16 support
eeverman/andhow pull request #573
Opened 2021-08-27 21:24 UTC by alex-kar

Fixes #566

* Replace `mockito-all` with latest `mockito-core`

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-08-28 19:32 UTC, eeverman requested changes
One minor change to remove my unneeded dependency, but this is a great fix.  I was worried that something had changed in the JVM that required changes in the project - glad that is not the case.
Nice fix!

2021-08-28 19:32 UTC, eeverman commented on andhow-junit5-extensions/pom.xml
> +			<version>3.12.4</version>
This dependency can just be deleted.  Its inherited from the parent pom, which you already fixed.

2021-08-28 20:25 UTC, alex-kar commented on andhow-junit5-extensions/pom.xml
> +			<version>3.12.4</version>
Fixed

2021-08-29 02:21 UTC, eeverman approved these changes

2021-08-29 02:23 UTC, eeverman commented
Looks great.  I prefer to let people merge their own code - Please merge if you are happy with it.

2021-08-29 08:10 UTC, merged