Fix loader setters
eeverman/andhow pull request #583
Opened 2021-09-03 23:19 UTC by alex-kar

Fixes #555 

 * Fix setters for loaders.
 * Fix/add unit tests.

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-09-03 23:53 UTC, alex-kar commented
@eeverman Please, check the build script. Failed to install maven.

2021-09-04 01:15 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +		}
This is a minor point, but these could just be set back to null with no logic.  That would return it back to its initial state and completely release resources.

2021-09-04 01:23 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java
> +		LoaderValues result = cll.load(appDef, appValuesBuilder);
The name 'cll' is not important, but in case you are wondering, that probably originated with a test for the StdMainStringArgsLoader, which might also be called the **C**ommand **L**ine **L**oader, since it loads arguments from the Command Line (and received by the main(String[] args)).

2021-09-04 02:49 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java
> +	public void nullValuesTest() {
There are actually two methods that set property values that should have a 'set null' test:  The `setPropertyValues` method (tested here) and the `setKeyObjectPairValues` method, which I think is not tested for `null`.

2021-09-04 02:53 UTC, eeverman requested changes
This is a good change overall, but it would be nice to pick up a few more lines that are missed in the testing.

2021-09-04 05:31 UTC, eeverman commented
@alex-kar I missed your message about the appveyor build script.  I just logged into Appveyor and was able to run it w/o problem.  I think it just hit a transient issue.

2021-09-04 20:48 UTC, alex-kar commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +		}
Fixed
Should we align MapLoader#releaseResources() ?
In current implementation clears the map
```
public void releaseResources() {
    if (map != null) {
        map.clear();
    }
}
```

2021-09-04 20:51 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java
> +		LoaderValues result = cll.load(appDef, appValuesBuilder);
Renamed to `loader`

2021-09-04 20:59 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +		}
All the loaders can use
```
[any resource] = null;
```
in `releaseResources()`.  At this point the loaders are done and they cannot be used again.  Resources aren't dumped immediately by the loader when the `load()` method completes because it can be useful to debug the state of how the load happened to have all that info.  But once the load succeeds completely, we don't want to hold any unneeded state because that would be held for the life of the application for no reason.

2021-09-04 21:19 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java
> +	public void nullValuesTest() {
Added tests.
For some reason I couldn't open it before, but now yes, I have access to it.

2021-09-04 21:53 UTC, alex-kar commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +		}
Fixed MapLoader#releaseResources as well

2021-09-05 03:07 UTC, eeverman commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +
I'm glad you caught this - potentially nulls.

Rather than initialize them, I propose leaving them as potential null and wrap each of the values.stream() w/ a null check:
```
if (values != null) {
  values.stream()....
}
```
`vvs` can just be initialized to the default ArrayList size, or use a ternary expression for null.
I

2021-09-05 03:09 UTC, eeverman requested changes
One more small change - See note on the FixedValueLoader.
Otherwise I think its ready to go.

2021-09-05 08:18 UTC, alex-kar commented on andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java
> +
Fixed

2021-09-05 15:34 UTC, eeverman approved these changes
Perfect - Thank you!

2021-09-05 15:45 UTC, merged