Skip unneeded artifacts on deploy
eeverman/andhow pull request #593
Opened 2021-09-13 23:03 UTC by alex-kar

Fixes #499 

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-09-13 23:06 UTC, alex-kar commented
@eeverman Checked the fix by running `mvn clean deploy` and see what I have inside `./target/nexus-staging`.
Please, double check what actually will be uploaded into Sonatype snapshots.

2021-09-14 02:21 UTC, eeverman requested changes
This is a GREAT fix!  It has bugged me for a while that I couldn't turn off deployment for these files, and makes it confusing for someone looking in the repo to see what they need.

Two of the pom files need to be reverted due to my mistake.  I had forgotten I had added new modules since I wrote the ticket.

Thanks for the fix!

2021-09-14 02:21 UTC, eeverman commented on andhow-junit5-extensions/pom.xml
> +	</build>
Sorry - This is a new module added since I created the ticket (I just updated it now to reflect that).  This artifact is needed in the deployment.

2021-09-14 02:21 UTC, eeverman commented on andhow-shared-test-utils/pom.xml
> +</project>
Same - This is a new module added since I created the ticket.  This artifact is needed in the deployment.

2021-09-14 05:52 UTC, alex-kar commented on andhow-junit5-extensions/pom.xml
> +	</build>
Reverted

2021-09-14 05:52 UTC, alex-kar commented on andhow-shared-test-utils/pom.xml
> +</project>
Reverted

2021-09-14 16:11 UTC, eeverman approved these changes
Thank you for the fix!

2021-09-14 16:25 UTC, merged