StringValidator.Equals checks for null entries
eeverman/andhow pull request #626
Opened 2021-09-29 19:44 UTC by alex-kar

Fixes #473 

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

2021-09-29 22:32 UTC, eeverman requested changes
Nice work and an improvement of test coverage as well.
One small change to a validation message.

2021-09-29 22:32 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
> +		assertFalse(instance.isSpecificationValid());
Nice catch to test this empty constructor

2021-09-29 22:32 UTC, eeverman commented on andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
> +	}
I think this should be updated to:
`The list must contain at least one value and none of the values can be null`

Referring to 'Equals list' won't make sense to the user any more, now that we have changed the builder method to `oneOf`.

2021-09-30 05:22 UTC, alex-kar commented on andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
> +	}
Updated the message

2021-09-30 05:49 UTC, eeverman approved these changes
Looks great!

2021-09-30 05:58 UTC, merged